name: 02 - Contexts, Env Vars and Secrets

on: 
  push:
    branches: [ "main" ]
    paths:
      - 'fase-03-ci-cd-orchestration/07-github-actions/**'
      - '.github/workflows/02-contexts-and-secrets.yml'
  workflow_dispatch:

env:
  ENVIRONMENT: "staging"
  LAB_NAME: "07-github-actions"

jobs:
  job-env-and-secrets:
    name: Test Environment Variables & Secret Masking
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Probar variables de entorno y contexts
        env:
          STEP_SPECIFIC_VAR: "Solo visible en este step"
        run: |
          echo "=== VARIABLES Y CONTEXTOS ==="
          echo "Entorno global: $ENVIRONMENT"
          echo "Lab: $LAB_NAME"
          echo "Var de Step: $STEP_SPECIFIC_VAR"
          echo "Actor desde Contexto: ${{ github.actor }}"

      - name: Demostrar enmascaramiento de Secrets por GitHub
        env:
          MY_SECRET: ${{ secrets.LAB_TEST_SECRET }}
        run: |
          echo "=== PRUEBA DE SEGURIDAD DE SECRETS ==="
          echo "Intentando imprimir el secret directamente:"
          echo "El valor del secret es: $MY_SECRET"

  job_dependent:
    name: Secondary Job (Sequential Execution)
    needs: job-env-and-secrets # Espera a que el anterior Job termine con éxito
    runs-on: ubuntu-latest

    steps:
      - name: Confirmación de orden de ejecución
        run: |
          echo "Este Job se ejecutó ÚNICAMENTE porquie 'job-env-and-secrets' finalizó correctamente."
